algoritmo "ex. 3"
var
   aluno1 ,aluno2: caractere
   n1, n2: real
inicio

   escreva("Digite o nome do primeiro aluno: ")
   leia(aluno1)

   escreva("Digite a nota do primeiro aluno: ")
   leia(n1)

   escreva("Digite o nome do segundo aluno: ")
   leia(aluno2)

   escreva("Digite a nota do segundo aluno: ")
   leia(n2)

   escrevaL("")

   escrevaL("Primeiro aluno: ", aluno1)
   escrevaL("Nota: ", n1)

   escrevaL("Segundo aluno: ", aluno2)
   escrevaL("Nota: ", n2)
   
fimalgoritmo
